# Base configs
baseurl: "https://manuelfdez2.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Bienvenidos a mi galería fotográfica"
subtitle: "See the world through my eyes!"
author: "Manuel Fernández"
header:
 title: "Galería"
 subtitle: "by manuelfdez2"
footer:
 name: "Sobre mí"
 bio: "Soy un joven aficionado a la fotografía, en mis ratos libres me encanta pasear por la naturaleza acompañado de mi cámara para inmortalizar momentos."
/web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/ManuFdez25"
  instagram: "https://www.instagram.com/manuelfdez2"
  github: "https://www.github.com/manuelfdez2"
